# TG-KITPVP Configuration File

settings:
  arena-world: "world"
  spawn-on-join: true
  spawn-on-death: true
  refill-health-on-kit: true
  refill-hunger-on-kit: true
  kit-cooldown: 30
  prevent-item-drop: true
  prevent-item-pickup: true
  auto-respawn-delay: 20

spawn:
  world: "world"
  x: 0.5
  y: 64.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

arena:
  enabled: true
  min-x: -100
  min-z: -100
  max-x: 100
  max-z: 100
  pvp-only-in-arena: true

economy:
  enabled: false
  kill-reward: 10.0
  death-penalty: 5.0
  streak-bonus: 2.0

kits:
  warrior:
    name: "&c&lWarrior"
    description: "&7A balanced fighter with sword and armor"
    icon: IRON_SWORD
    permission: ""
    items:
      helmet:
        material: IRON_HELMET
        enchantments:
          PROTECTION_ENVIRONMENTAL: 2
      chestplate:
        material: IRON_CHESTPLATE
        enchantments:
          PROTECTION_ENVIRONMENTAL: 2
      leggings:
        material: IRON_LEGGINGS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 2
      boots:
        material: IRON_BOOTS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 2
      slot-0:
        material: IRON_SWORD
        enchantments:
          DAMAGE_ALL: 2
      slot-1:
        material: BOW
        enchantments:
          ARROW_DAMAGE: 1
      slot-8:
        material: ARROW
        amount: 32
      slot-2:
        material: GOLDEN_APPLE
        amount: 3
    effects:
      - REGENERATION:0:5

  archer:
    name: "&a&lArcher"
    description: "&7Master of ranged combat"
    icon: BOW
    permission: ""
    items:
      helmet:
        material: LEATHER_HELMET
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
          PROTECTION_PROJECTILE: 3
      chestplate:
        material: CHAINMAIL_CHESTPLATE
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
      leggings:
        material: CHAINMAIL_LEGGINGS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
      boots:
        material: LEATHER_BOOTS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
      slot-0:
        material: STONE_SWORD
      slot-1:
        material: BOW
        enchantments:
          ARROW_DAMAGE: 3
          ARROW_INFINITE: 1
      slot-8:
        material: ARROW
        amount: 1
      slot-2:
        material: GOLDEN_APPLE
        amount: 2
    effects:
      - SPEED:0:999999

  tank:
    name: "&9&lTank"
    description: "&7Heavy armor and high defense"
    icon: DIAMOND_CHESTPLATE
    permission: ""
    items:
      helmet:
        material: DIAMOND_HELMET
        enchantments:
          PROTECTION_ENVIRONMENTAL: 3
      chestplate:
        material: DIAMOND_CHESTPLATE
        enchantments:
          PROTECTION_ENVIRONMENTAL: 3
      leggings:
        material: DIAMOND_LEGGINGS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 3
      boots:
        material: DIAMOND_BOOTS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 3
      slot-0:
        material: STONE_SWORD
        enchantments:
          DAMAGE_ALL: 1
      slot-1:
        material: SHIELD
      slot-2:
        material: GOLDEN_APPLE
        amount: 5
    effects:
      - DAMAGE_RESISTANCE:0:999999
      - SLOW:0:999999

  mage:
    name: "&d&lMage"
    description: "&7Potion master with magical abilities"
    icon: POTION
    permission: ""
    items:
      helmet:
        material: GOLDEN_HELMET
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
      chestplate:
        material: GOLDEN_CHESTPLATE
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
      leggings:
        material: GOLDEN_LEGGINGS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
      boots:
        material: GOLDEN_BOOTS
        enchantments:
          PROTECTION_ENVIRONMENTAL: 1
      slot-0:
        material: STONE_SWORD
      slot-1:
        material: SPLASH_POTION
        potion: INSTANT_DAMAGE
        amount: 3
      slot-2:
        material: SPLASH_POTION
        potion: SLOWNESS
        amount: 2
      slot-3:
        material: SPLASH_POTION
        potion: WEAKNESS
        amount: 2
      slot-4:
        material: POTION
        potion: INSTANT_HEAL
        amount: 5
      slot-5:
        material: GOLDEN_APPLE
        amount: 2
    effects:
      - REGENERATION:0:999999

  assassin:
    name: "&8&lAssassin"
    description: "&7Fast and stealthy killer"
    icon: DIAMOND_SWORD
    permission: ""
    items:
      helmet:
        material: LEATHER_HELMET
      chestplate:
        material: LEATHER_CHESTPLATE
      leggings:
        material: LEATHER_LEGGINGS
      boots:
        material: LEATHER_BOOTS
        enchantments:
          PROTECTION_FALL: 4
      slot-0:
        material: DIAMOND_SWORD
        enchantments:
          DAMAGE_ALL: 3
      slot-1:
        material: POTION
        potion: INVISIBILITY
        amount: 2
      slot-2:
        material: GOLDEN_APPLE
        amount: 2
    effects:
      - SPEED:1:999999
      - JUMP:1:999999

messages:
  prefix: "&8[&c&lTG-KITPVP&8] &r"
  joined-arena: "&aYou have joined the arena!"
  left-arena: "&cYou have left the arena!"
  kit-selected: "&aYou have selected the {kit} kit!"
  kit-cooldown: "&cYou must wait {time} seconds before changing kits!"
  kill: "&aYou killed {player}! &e+{reward} coins"
  death: "&cYou were killed by {player}!"
  killstreak: "&6You are on a {streak} kill streak!"
  reload-success: "&aConfiguration reloaded successfully!"
  no-permission: "&cYou don't have permission to do that!"
  not-in-arena: "&cYou are not in the arena!"
  kit-not-found: "&cKit not found!"
  spawn-not-set: "&cSpawn location is not set!"
  leaderboard-header: "&8&m----&r &c&lTop 10 Players &8&m----&r"
  leaderboard-entry: "&e#{rank} &f{player} &7- &a{kills} kills"
